### ISSUE TITLE
Error when Building

### ISSUE THREAD

**Issue by stevesob** [joshnuss/svelte-snowpack-template#1]
I get the following error when trying to build. Any ideas how to fix?

 npm run build

> @ build C:\Dev2020\Snowpack\test
> snowpack build

[svelte-check] ====================================
[svelte-check] svelte-check found 0 errors, 0 warnings and 0 hints
[eslint] Oops! Something went wrong! :(

ESLint: 7.12.0

No files matching the pattern "'src/**/*.{js,jsx,ts,tsx}'" were found.
Please check for typing mistakes in the pattern.
[eslint] Error: Command failed with exit code 2: eslint 'src/**/*.{js,jsx,ts,tsx}'

Oops! Something went wrong! :(

ESLint: 7.12.0

No files matching the pattern "'src/**/*.{js,jsx,ts,tsx}'" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `snowpack build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steve\AppData\Roaming\npm-cache\_logs\2020-10-24T15_40_02_450Z-debug.log

[2020-10-24T15_40_02_450Z-debug.log](https://github.com/joshnuss/svelte-snowpack-template/files/5433123/2020-10-24T15_40_02_450Z-debug.log)

**Comment by joshnuss** [comment]
Hi @stevesob,

I see you're using Windows which I haven't tested. I'm on Linux.

Can you try it with WSL?

**Comment by stevesob** [comment]
Thanks for your help!

I created a new app from the Snowpack-svelte template and added Webpack on
build mainly to minimize.

It is located at:
https://github.com/stevesob/snowpack-svelte-webpack-template

I'm very new to the JS build technology so this is a learning experience.
Any help is appreciated.

**Comment by joshnuss** [comment]
Looks good!

Maybe the problem you are having is only for the `eslint` command.
You can try removing it in `snowpack.config.js`.

I'm gonna close the issue for now, but let me know if you still need help with this template.
